name: Publish To NPMJS

on:
  workflow_dispatch: 

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'publish npm'
    environment: npm
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.13.0
          registry-url: https://registry.npmjs.org/
          
      - name: npm publish
        run: |
          cd $GITHUB_WORKSPACE/Loxodon.Framework/Assets/LoxodonFramework
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        
